### ISSUE TITLE
Make denominations config save as multi-line

### ISSUE THREAD

**Issue by benjaminiserman** [benjaminiserman/WingsContracts#8]
It should look like:
```toml
[General]
#Comma-separated list of reward items that can be automatically converted by portals into other denominations. Multiple lists may be provided, separated by semicolons.
denominations = """
    minecraft:emerald = 1, \
    minecraft:emerald_block = 9; \
    
    minecraft:diamond = 1, \
    minecraft:diamond_block = 9; \
    
    numismatics:spur = 1, \
    numismatics:bevel = 8, \
    numismatics:sprocket = 16, \
    numismatics:cog = 64, \
    numismatics:crown = 512, \
    numismatics:sun = 4096, \
    test:xyz = 100; \
"""
```

instead of:
```toml
[General]
#Comma-separated list of reward items that can be automatically converted by portals into other denominations. Multiple lists may be provided, separated by semicolons.
denominations = "\n            minecraft:emerald = 1, \n            minecraft:emerald_block = 9;\n            \n            minecraft:diamond = 1, \n            minecraft:diamond_block = 9;\n            \n            numismatics:spur = 1,\n            numismatics:bevel = 8,\n            numismatics:sprocket = 16,\n            numismatics:cog = 64,\n            numismatics:crown = 512,\n            numismatics:sun = 4096,\n            test:xyz = 100;\n        "

```
